# specify the node base image with your desired version node:<version>
FROM ubuntu

ARG branch=main
ARG ssh_key_path=~/.ssh/id_github
ARG config_path

WORKDIR /home

# Update aptitude with new repo
RUN apt-get update

# Install software 
RUN apt-get install -y git

# Make ssh dir
RUN mkdir /root/.ssh/

# Copy over private key, and set permissions
# Warning! Anyone who gets their hands on this image will be able
# to retrieve this private key file from the corresponding image layer
ADD $ssh_key_path /root/.ssh/id_github
RUN  echo "    IdentityFile /root/.ssh/id_github" >> /etc/ssh/ssh_config

# Create known_hosts
RUN touch /root/.ssh/known_hosts
# Add bitbuckets key
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts


### KVASER Driver

RUN apt-get update
RUN apt-get install -y build-essential 
RUN apt-get install -y linux-headers-`uname -r` 
RUN apt-get install -y cmake make
RUN apt-get install -y wget

RUN wget --content-disposition "https://www.kvaser.com/downloads-kvaser/?utm_source=software&utm_ean=7330130980754&utm_status=latest"
RUN tar xvzf linuxcan.tar.gz
WORKDIR /home/linuxcan/canlib
RUN make
RUN make install
RUN /usr/doc/canlib/examples/listChannels

WORKDIR /home/

# Clone the conf files into the docker container
RUN git clone git@github.com:SpaceTeam/llserver_ecui_houbolt.git
WORKDIR /home/llserver_ecui_houbolt

RUN ls -la

# WORKDIR /home/web_ecui_houbolt
# RUN ls -la
RUN git checkout $branch
RUN git pull
RUN git submodule init
RUN git submodule update

RUN cmake . -D NO_PYTHON=true
RUN make -j

RUN echo "../config_ecui" >> configPath.txt

ENTRYPOINT ./llserver_ecui_houbolt