# specify the node base image with your desired version node:<version>
FROM node:16
# replace this with your application's default port
EXPOSE 5555
EXPOSE 80

WORKDIR /home

# Update aptitude with new repo
RUN apt-get update

# Install software 
RUN apt-get install -y git

RUN npm install -g nodemon

ADD install_docker.sh /home
RUN ./install_docker.sh
RUN rm install_docker.sh

WORKDIR /home/web_ecui_houbolt

ENV ECUI_CONFIG_PATH=/home/config_ecui

ENTRYPOINT npm install && cd client/pnid_houbolt && npm install && cd ../../ && nodemon server